//ACA VA LA VISTA GENERAL PARA TODOS LOS PROYECTOS
//POR PROPS VIENE LA DATA QUE VA A ESTAR EN UN ARRAY DE OBJETOS
//CADA OBJETO VA A SER LA DATA DE CADA PROYECTO
//ESA DATA SE VA A VOLCAR ACÁ PARA QUE TODOS LOS PROYECTOS TENGAN EL MISMO DISEÑO

//FALTA: HACER EN APP.TSX LA RUTA A CADA PROYECTO path=:nombredelproyecto

//
